apiVersion: "rbac.istio.io/v1alpha1"
kind: RbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
#    namespaces: ["qa"]
    services: ["callme-service.qa.svc.cluster.local"]