kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: qa
  name: secretreader-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secretreader-rolebinding
  namespace: qa
subjects:
  - kind: User
    name: user-read-secret
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secretreader-role
  apiGroup: rbac.authorization.k8s.io
