apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: callme-role-bind
  namespace: qa
spec:
  subjects:
    - user: "cluster.local/ns/qa/sa/callme-sa"
  roleRef:
    kind: ServiceRole
    name: "callme-role"