apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: service-admin-binding
  namespace: qa
spec:
  subjects:
    - user: "*"
  roleRef:
    kind: ServiceRole
    name: "service-admin"