server:
  port: 8091

spring:
  application:
    name: Callme

bizdirect:

  app-version: 1.0.0-SNAPSHOT

        




  #Rest-client configurations
  rest-client:
    connection-timeout-ms: 5000
    read-timeout-ms: 5000

  cache:
    redis:
      host: localhost
      port: 6379
      database: 1
      max-wait-millis: 100
      max-idle: 100
      min-idle: 10
      max-total: 100
      connection-timeout-ms: 2000
      read-timeout-ms: 2000  
      

      

  service:
    hello:
      host: localhost
      port: 6565
      maxRetry: 3
    date:
      host: localhost
      port: 6565
      maxRetry: 3